# Generated by Django 4.2.29 on 2026-04-24 06:33

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blog_image_alter_blog_posted_alter_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-метка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 24, 9, 33, 51, 788760), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 24, 9, 33, 51, 789261), verbose_name='Дата комментария'),
        ),
        migrations.CreateModel(
            name='EducationalMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('short_description', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('material_type', models.CharField(choices=[('video', 'Видеолекция'), ('book', 'Учебник/Книга'), ('article', 'Статья'), ('presentation', 'Презентация'), ('test', 'Тест'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/%Y/%m/%d/')),
                ('file_link', models.URLField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Продолжительность')),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Образовательный материал',
                'verbose_name_plural': 'Образовательные материалы',
                'ordering': ['-published_date', 'title'],
            },
        ),
    ]
