# Generated by Django 4.2.29 on 2026-04-24 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_alter_blog_posted_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 24, 10, 15, 9, 969133), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 24, 10, 15, 9, 969633), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='material_type',
            field=models.CharField(choices=[('video', 'Видеолекция'), ('book', 'Учебник/Книга'), ('article', 'Статья'), ('course', 'Курс'), ('presentation', 'Презентация'), ('test', 'Тест'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип'),
        ),
    ]
