# Generated by Django 4.2.29 on 2026-04-26 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_blog_posted_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalmaterial',
            options={'ordering': ['-posted_at', 'title'], 'verbose_name': 'Образовательный материал', 'verbose_name_plural': 'Образовательные материалы'},
        ),
        migrations.RemoveField(
            model_name='educationalmaterial',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='educationalmaterial',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='educationalmaterial',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='educationalmaterial',
            name='level',
        ),
        migrations.RemoveField(
            model_name='educationalmaterial',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='educationalmaterial',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='educationalmaterial',
            name='views_count',
        ),
        migrations.AddField(
            model_name='educationalmaterial',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 26, 20, 12, 26, 576149), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 26, 20, 12, 26, 574146), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 26, 20, 12, 26, 574647), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='material_type',
            field=models.CharField(choices=[('video', 'Видеолекция'), ('book', 'Учебник/Книга'), ('article', 'Статья'), ('presentation', 'Презентация'), ('test', 'Тест'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='short_description',
            field=models.CharField(max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
