# Generated by Django 4.2.29 on 2026-04-26 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_educationalmaterial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 26, 21, 45, 58, 871602), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 26, 21, 45, 58, 872102), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 26, 21, 45, 58, 873103), verbose_name='Опубликовано'),
        ),
    ]
