# Generated by Django 4.2.29 on 2026-04-27 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category_image_alter_blog_posted_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 28, 2, 11, 9, 154935), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 4, 28, 2, 11, 9, 154935), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 28, 2, 11, 9, 156527), verbose_name='Опубликовано'),
        ),
    ]
